### ISSUE TITLE
Overview page on scverse.org

### ISSUE THREAD

**Issue by grst** [scverse/scverse-tutorials#43]
Following up on #2:

Tutorials will be scattered across different places (e.g. package repos) and we still want to collect them all in a single place.
In the foreseeable future, we won't be able to provide infrastructure for unified rendering of all those notebooks in a single place. We, therefore, decided to link to external tutorials from a single overview page. 

Next question is where this overview page lives:
 * https://scverse.org/learn (as suggested by @gtca)
 * https://scverse-tutorials.readthedocs.io/en/latest/index.html

**Pro website**
 * very prominent place
 * fits into scverse design
 * more flexible than being constrained to sphinx 
 * scope of this repo: just provide a place to store and render tutorials that don't fit anywhere else (i.e. are not package specific)

**Pro scverse-tutorials.readthedocs**
 * Maybe easier to find other tutorials for users that already browse tutorials here. 
 * scope of this repo: *The* central place for scverse tutorial, internal or external.

**Comment by ivirshup** [comment]
I think we could use scverse.org/learn, but also use sphinx for that page. The benefits would be:

* Intersphinx – so it's easier to keep links from breaking, and tell when they do break
* Card generation – we could automatically generate cards via inter sphinx
* Familiarity & consolidation – We all have to use sphinx anyways, one less thing to learn, but new things we do learn cross over more readily

I think the visual part can be worked around, since we could do custom CSS for sphinx.
